# Generated by Django 5.0.4 on 2024-05-10 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvancedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pp",
                    models.CharField(
                        choices=[
                            ("none", "-"),
                            ("bird", "Vogel"),
                            ("butterfly", "Schmetterling"),
                            ("cat", "Katze"),
                            ("dog", "Hund"),
                            ("duck", "Ente"),
                            ("jellyfish", "Qualle"),
                            ("owl", "Eule"),
                            ("panda", "Panda"),
                            ("penguin", "Pinguin"),
                            ("pig", "Schwein"),
                            ("rabbit", "Hase"),
                            ("sheep", "Schaf"),
                            ("snail", "Schnecke"),
                            ("snake", "Schlange"),
                            ("turkey", "Truthan"),
                            ("turtle", "Schildkröte"),
                        ],
                        default="none",
                        max_length=50,
                    ),
                ),
                ("biographie", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "discord_username",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "epicgames_username",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "facebook_username",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "instagram_username",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "linkedin_username",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "pinterest_username",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "playstation_username",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "reddit_username",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "snapchat_username",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "steam_username",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "threads_username",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "tiktok_username",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "twitter_username",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "xbox_username",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "xing_username",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "youtube_username",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("overtime_hours", models.FloatField(blank=True, null=True)),
                ("privacy", models.BooleanField(default=False)),
                ("terms", models.BooleanField(default=False)),
                ("disclaimer", models.BooleanField(default=False)),
                ("copyright", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advanced",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterfaceUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("light", "Hell"),
                            ("dark", "Dunkel"),
                            ("contrast", "Kontrast"),
                        ],
                        default="light",
                        max_length=50,
                    ),
                ),
                ("gender_neutral", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interface",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blocked",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blocked_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "friends",
                    models.ManyToManyField(
                        blank=True, related_name="friends", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Warn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("abuse", "Missbrauch von Privilegien"),
                            ("antisemitism", "Antisemitismus"),
                            ("blackmailing", "Erpressung"),
                            ("bullying", "Cybermobbing"),
                            (
                                "child_like_imagery",
                                "Darstellung von kinderähnlichen Merkmalen",
                            ),
                            ("christophobia", "Christophobie"),
                            ("cow", "Wortwahl"),
                            ("discrimination", "Diskriminierung"),
                            ("doxxing", "Doxxing"),
                            ("exploitative_content", "Ausbeuterische Inhalte"),
                            ("fascism", "Faschismus"),
                            ("grooming", "Cybergrooming"),
                            ("harassment", "Belästigung"),
                            ("hatespeech", "Hassrede"),
                            ("homophobia", "Homophobie"),
                            ("illegal_content", "Illegale Inhalte"),
                            ("islamophobia", "Islamophobie"),
                            ("misinformation", "Falschinformationen"),
                            ("pornography", "Pornografie"),
                            ("propaganda", "Propaganda"),
                            ("racism", "Rassismus"),
                            ("relativisation", "Relativierung"),
                            ("scam", "Betrug"),
                            ("sexism", "Sexismus"),
                            ("spam", "Spam"),
                            ("swearword", "Beleidigung"),
                            ("threat", "Drohung"),
                            ("violent_content", "Gewaltbasierter Inhalt"),
                            ("whataboutism", "Whataboutismus"),
                            ("xenophobia", "Fremdenfeindlichkeit"),
                        ],
                        default="abuse",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
